title: Continuity Services
description: Documentation for Continuity Services
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/continuity.png"

url: https://kosteh.github.io/cnt-doc

# Remove if you don't want this link to appear on your pages
aux_links: 
  Continuity Services Docs: https://github.com/kosteh/cnt-doc

# Version of mermaid library for drawing diagrams
mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  # version: "10.0.0"
  # WORKS: path: https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.6.3/mermaid.min.js
  path: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
