title: Continuity Services
description: Documentation for Continuity Services
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/continuity.png"

url: https://kosteh.github.io/cnt-doc

# Remove if you don't want this link to appear on your pages
aux_links: 
  Continuity Services Docs: https://github.com/kosteh/cnt-doc

# Version of mermaid library for drawing diagrams
mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
  # path: https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.0.2/mermaid.min.js
