title: Continuity Services
description: Documentation for Continuity Services
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/continuity.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/continuity.png"

# Set the base_url
url: https://kosteh.github.io/cnt-doc

# Remove if you don't want this link to appear on your pages
aux_links: 
  Continuity Services Docs: https://github.com/kosteh/cnt-doc

# Version of mermaid library for drawing diagrams
mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  # version: "9.1.3"
  version: "9.4.3"
  # WERKT path: https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.0.2/mermaid.min.js

# Callout definitions
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
